=== SrPozuelo/LMGSI/115LMSGIProyectoLMSGI/ud4/02/02.dtd
<!ELEMENT biblioteca (libro)+>
<!ELEMENT libro (título, autores, año)>
<!ELEMENT título (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellido, nacionalidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ATTLIST libro idlibro ID #REQUIRED>
<!ATTLIST libro género CDATA #IMPLIED>
<!ATTLIST libro idioma CDATA "Español">
<!ATTLIST libro formato (impreso|digital) "impreso">
<!ATTLIST libro ref IDREFS #IMPLIED>

=== SrPozuelo/LMGSI/115LMSGIProyectoLMSGI/ud4/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "02.dtd">
<biblioteca>
    <libro idlibro="libro1" género="novela">
        <título>Punto para los locos</título>
        <autores>
            <autor>
                <nombre>Ángel</nombre>
                <apellido>Martín</apellido>
                <nacionalidad>Español</nacionalidad>
            </autor>
        </autores>
        <año>2024</año>
    </libro>
</biblioteca>
